# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=127, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=127, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='Почтовый адрес')),
            ],
            options={
                'verbose_name_plural': 'Авторы',
                'verbose_name': 'Автор',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AddField(
            model_name='post',
            name='post_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
