# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-11-24 17:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='timepublish',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
